// Code generated by "stringer -type=EdgeState"; DO NOT EDIT

package ghs

import "fmt"

const _EdgeState_name = "EdgeStateBasicEdgeStateBranchEdgeStateRejected"

var _EdgeState_index = [...]uint8{0, 14, 29, 46}

func (i EdgeState) String() string {
	if i < 0 || i >= EdgeState(len(_EdgeState_index)-1) {
		return fmt.Sprintf("EdgeState(%d)", i)
	}
	return _EdgeState_name[_EdgeState_index[i]:_EdgeState_index[i+1]]
}
