// generated by stringer -type=EdgeState; DO NOT EDIT

package ghs

import "fmt"

const _EdgeState_name = "EdgeStateBasicEdgeStateBranchEdgeStateRejected"

var _EdgeState_index = [...]uint8{14, 29, 46}

func (i EdgeState) String() string {
	if i < 0 || i >= EdgeState(len(_EdgeState_index)) {
		return fmt.Sprintf("EdgeState(%d)", i)
	}
	hi := _EdgeState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _EdgeState_index[i-1]
	}
	return _EdgeState_name[lo:hi]
}
