// generated by stringer -type=MessageType; DO NOT EDIT

package ghs

import "fmt"

const _MessageType_name = "MessageHelloMessageBroadcastMessageConvergeCast"

var _MessageType_index = [...]uint8{12, 28, 47}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	hi := _MessageType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _MessageType_index[i-1]
	}
	return _MessageType_name[lo:hi]
}
