// Code generated by protoc-gen-go.
// source: tracer.proto
// DO NOT EDIT!

/*
Package tracer is a generated protocol buffer package.

It is generated from these files:
	tracer.proto

It has these top-level messages:
	LogRequest
	LogResponse
	NodeUpdateRequest
	NodeUpdateResponse
	EdgeUpdateRequest
	EdgeUpdateResponse
	MessageUpdateRequest
	MessageUpdateResponse
*/
package tracer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LogRequest struct {
	Message string `protobuf:"bytes,1,opt,name=Message" json:"Message,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LogResponse struct {
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeUpdateRequest struct {
}

func (m *NodeUpdateRequest) Reset()                    { *m = NodeUpdateRequest{} }
func (m *NodeUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeUpdateRequest) ProtoMessage()               {}
func (*NodeUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NodeUpdateResponse struct {
}

func (m *NodeUpdateResponse) Reset()                    { *m = NodeUpdateResponse{} }
func (m *NodeUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeUpdateResponse) ProtoMessage()               {}
func (*NodeUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type EdgeUpdateRequest struct {
}

func (m *EdgeUpdateRequest) Reset()                    { *m = EdgeUpdateRequest{} }
func (m *EdgeUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*EdgeUpdateRequest) ProtoMessage()               {}
func (*EdgeUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type EdgeUpdateResponse struct {
}

func (m *EdgeUpdateResponse) Reset()                    { *m = EdgeUpdateResponse{} }
func (m *EdgeUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*EdgeUpdateResponse) ProtoMessage()               {}
func (*EdgeUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type MessageUpdateRequest struct {
}

func (m *MessageUpdateRequest) Reset()                    { *m = MessageUpdateRequest{} }
func (m *MessageUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*MessageUpdateRequest) ProtoMessage()               {}
func (*MessageUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type MessageUpdateResponse struct {
}

func (m *MessageUpdateResponse) Reset()                    { *m = MessageUpdateResponse{} }
func (m *MessageUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageUpdateResponse) ProtoMessage()               {}
func (*MessageUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*LogRequest)(nil), "tracer.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "tracer.LogResponse")
	proto.RegisterType((*NodeUpdateRequest)(nil), "tracer.NodeUpdateRequest")
	proto.RegisterType((*NodeUpdateResponse)(nil), "tracer.NodeUpdateResponse")
	proto.RegisterType((*EdgeUpdateRequest)(nil), "tracer.EdgeUpdateRequest")
	proto.RegisterType((*EdgeUpdateResponse)(nil), "tracer.EdgeUpdateResponse")
	proto.RegisterType((*MessageUpdateRequest)(nil), "tracer.MessageUpdateRequest")
	proto.RegisterType((*MessageUpdateResponse)(nil), "tracer.MessageUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for TraceService service

type TraceServiceClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	NodeUpdate(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeUpdateResponse, error)
	EdgeUpdate(ctx context.Context, in *EdgeUpdateRequest, opts ...grpc.CallOption) (*EdgeUpdateResponse, error)
	MessageUpdate(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error)
}

type traceServiceClient struct {
	cc *grpc.ClientConn
}

func NewTraceServiceClient(cc *grpc.ClientConn) TraceServiceClient {
	return &traceServiceClient{cc}
}

func (c *traceServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := grpc.Invoke(ctx, "/tracer.TraceService/Log", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceServiceClient) NodeUpdate(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeUpdateResponse, error) {
	out := new(NodeUpdateResponse)
	err := grpc.Invoke(ctx, "/tracer.TraceService/NodeUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceServiceClient) EdgeUpdate(ctx context.Context, in *EdgeUpdateRequest, opts ...grpc.CallOption) (*EdgeUpdateResponse, error) {
	out := new(EdgeUpdateResponse)
	err := grpc.Invoke(ctx, "/tracer.TraceService/EdgeUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceServiceClient) MessageUpdate(ctx context.Context, in *MessageUpdateRequest, opts ...grpc.CallOption) (*MessageUpdateResponse, error) {
	out := new(MessageUpdateResponse)
	err := grpc.Invoke(ctx, "/tracer.TraceService/MessageUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TraceService service

type TraceServiceServer interface {
	Log(context.Context, *LogRequest) (*LogResponse, error)
	NodeUpdate(context.Context, *NodeUpdateRequest) (*NodeUpdateResponse, error)
	EdgeUpdate(context.Context, *EdgeUpdateRequest) (*EdgeUpdateResponse, error)
	MessageUpdate(context.Context, *MessageUpdateRequest) (*MessageUpdateResponse, error)
}

func RegisterTraceServiceServer(s *grpc.Server, srv TraceServiceServer) {
	s.RegisterService(&_TraceService_serviceDesc, srv)
}

func _TraceService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TraceServiceServer).Log(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _TraceService_NodeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(NodeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TraceServiceServer).NodeUpdate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _TraceService_EdgeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EdgeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TraceServiceServer).EdgeUpdate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _TraceService_MessageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MessageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(TraceServiceServer).MessageUpdate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _TraceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tracer.TraceService",
	HandlerType: (*TraceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _TraceService_Log_Handler,
		},
		{
			MethodName: "NodeUpdate",
			Handler:    _TraceService_NodeUpdate_Handler,
		},
		{
			MethodName: "EdgeUpdate",
			Handler:    _TraceService_EdgeUpdate_Handler,
		},
		{
			MethodName: "MessageUpdate",
			Handler:    _TraceService_MessageUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x29, 0x4a, 0x4c,
	0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x64, 0xb9, 0xb8,
	0x7c, 0xf2, 0xd3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb9, 0xd8, 0x7d, 0x53,
	0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x95, 0x78, 0xb9, 0xb8, 0xc1,
	0xd2, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0xc2, 0x5c, 0x82, 0x7e, 0xf9, 0x29, 0xa9, 0xa1,
	0x05, 0x29, 0x89, 0x25, 0xa9, 0x50, 0x4d, 0x4a, 0x22, 0x5c, 0x42, 0xc8, 0x82, 0x08, 0xa5, 0xae,
	0x29, 0xe9, 0x98, 0x4a, 0x91, 0x05, 0xa1, 0x4a, 0xc5, 0xb8, 0x44, 0xa0, 0xb6, 0xa2, 0xaa, 0x16,
	0xe7, 0x12, 0x45, 0x13, 0x87, 0x68, 0x30, 0x9a, 0xc6, 0xc4, 0xc5, 0x13, 0x02, 0x72, 0x7f, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1e, 0x17, 0x33, 0xd0, 0x99, 0x42, 0x42, 0x7a, 0x50,
	0x3f, 0x22, 0xbc, 0x24, 0x25, 0x8c, 0x22, 0x06, 0x31, 0x40, 0xc8, 0x99, 0x8b, 0x0b, 0xe1, 0x64,
	0x21, 0x49, 0x98, 0x12, 0x0c, 0xbf, 0x49, 0x49, 0x61, 0x93, 0x42, 0x18, 0x82, 0xf0, 0x0c, 0xc2,
	0x10, 0x0c, 0x5f, 0x23, 0x0c, 0xc1, 0xf4, 0xbb, 0x90, 0x0f, 0x17, 0x2f, 0x8a, 0x1f, 0x85, 0x64,
	0x60, 0x8a, 0xb1, 0x05, 0x89, 0x94, 0x2c, 0x0e, 0x59, 0x88, 0x69, 0x49, 0x6c, 0xe0, 0xc8, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x7e, 0x48, 0xf4, 0xec, 0x01, 0x00, 0x00,
}
