// Code generated by protoc-gen-go.
// source: graphalg.proto
// DO NOT EDIT!

/*
Package graphalg is a generated protocol buffer package.

It is generated from these files:
	graphalg.proto

It has these top-level messages:
	Weight
*/
package graphalg

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Weight struct {
	Cost  float64 `protobuf:"fixed64,1,opt,name=cost" json:"cost,omitempty"`
	LsnID string  `protobuf:"bytes,2,opt,name=lsnID" json:"lsnID,omitempty"`
	MsnID string  `protobuf:"bytes,3,opt,name=msnID" json:"msnID,omitempty"`
}

func (m *Weight) Reset()         { *m = Weight{} }
func (m *Weight) String() string { return proto.CompactTextString(m) }
func (*Weight) ProtoMessage()    {}
