// Code generated by protoc-gen-gogo.
// source: ping.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	ping.proto

It has these top-level messages:
	PingRequest
	PingReply
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type PingRequest struct {
	Time             *uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Count            *uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Hostid           []byte  `protobuf:"bytes,3,opt,name=hostid" json:"hostid,omitempty"`
	Test             *string `protobuf:"bytes,4,opt,name=test" json:"test,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto1.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}

func (m *PingRequest) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PingRequest) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PingRequest) GetHostid() []byte {
	if m != nil {
		return m.Hostid
	}
	return nil
}

func (m *PingRequest) GetTest() string {
	if m != nil && m.Test != nil {
		return *m.Test
	}
	return ""
}

type PingReply struct {
	Time             *uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	TimeDelta        *int64  `protobuf:"varint,2,opt,name=timeDelta" json:"timeDelta,omitempty"`
	Count            *uint32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	CountMiss        *int32  `protobuf:"varint,4,opt,name=countMiss" json:"countMiss,omitempty"`
	Hostid           []byte  `protobuf:"bytes,5,opt,name=hostid" json:"hostid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto1.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}

func (m *PingReply) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PingReply) GetTimeDelta() int64 {
	if m != nil && m.TimeDelta != nil {
		return *m.TimeDelta
	}
	return 0
}

func (m *PingReply) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PingReply) GetCountMiss() int32 {
	if m != nil && m.CountMiss != nil {
		return *m.CountMiss
	}
	return 0
}

func (m *PingReply) GetHostid() []byte {
	if m != nil {
		return m.Hostid
	}
	return nil
}

func init() {
}
