// Code generated by protoc-gen-gogo.
// source: ping.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	ping.proto

It has these top-level messages:
	PingRequest
	PingReply
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type PingRequest struct {
	Time             *uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Count            *uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Hostid           []byte  `protobuf:"bytes,3,opt,name=hostid" json:"hostid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto1.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}

func (m *PingRequest) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PingRequest) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PingRequest) GetHostid() []byte {
	if m != nil {
		return m.Hostid
	}
	return nil
}

type PingReply struct {
	TimeSent         *uint64 `protobuf:"varint,1,opt,name=timeSent" json:"timeSent,omitempty"`
	TimeIn           *uint64 `protobuf:"varint,2,opt,name=timeIn" json:"timeIn,omitempty"`
	TimeOut          *uint64 `protobuf:"varint,3,opt,name=timeOut" json:"timeOut,omitempty"`
	Count            *uint32 `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	CountMiss        *int32  `protobuf:"varint,5,opt,name=countMiss" json:"countMiss,omitempty"`
	Hostid           []byte  `protobuf:"bytes,6,opt,name=hostid" json:"hostid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto1.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}

func (m *PingReply) GetTimeSent() uint64 {
	if m != nil && m.TimeSent != nil {
		return *m.TimeSent
	}
	return 0
}

func (m *PingReply) GetTimeIn() uint64 {
	if m != nil && m.TimeIn != nil {
		return *m.TimeIn
	}
	return 0
}

func (m *PingReply) GetTimeOut() uint64 {
	if m != nil && m.TimeOut != nil {
		return *m.TimeOut
	}
	return 0
}

func (m *PingReply) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PingReply) GetCountMiss() int32 {
	if m != nil && m.CountMiss != nil {
		return *m.CountMiss
	}
	return 0
}

func (m *PingReply) GetHostid() []byte {
	if m != nil {
		return m.Hostid
	}
	return nil
}

func init() {
}
